version: 0.0
os: linux
files:
 - source: /src
   destination: /home/ubuntu/flask-test
 - source: requirements.txt
   destination: /home/ubuntu/flask-test
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-west-1:558435908302:task-definition/ecs-demo-task-definition:revision-number"
        LoadBalancerInfo:
          ContainerName: "Sample CodeDeploy"
          ContainerPort: 5000
hooks:
  AfterInstall:
   - location: scripts/before_install
     timeout: 300
     runas: root
   - location: scripts/start_server
     timeout: 300
     runas: root