version: 0.0
os: linux
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-west-1:558435908302:task-definition/ecs-demo-task-definition:revision-number"
        LoadBalancerInfo:
          ContainerName: "Sample CodeDeploy"
          ContainerPort: 9000
hooks:
  AfterInstall:
   - location: scripts/before_install
     timeout: 10000
     runas: root
   - location: scripts/start_server
     timeout: 10000
     runas: root