#!/bin/bash
current_path="$0"
project_folder=${current_path%%/scripts*}
cd $project_folder
activate () {
  . $project_folder/venv/bin/activate
}
cd examples/tutorial
pwd
$project_folder/venv/bin/flask --app flaskr init-db
$project_folder/venv/bin/flask --app flaskr run -p 9000